try:
    print(2 / 0)
except Exception as e:
    print(e)
